project:
  type: website

website:
  title: "CCO221 - Métodos y técnicas de investigación 1"
  navbar:
    left:
      - href: index.qmd
        text: Acerca de
      - text: Clases prácticas
        menu: 
          - href: clasep2.qmd
            text: Clase práctica 2

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

