project:
  type: website
  render: 
    - "*.Rmd"
    - "*.rmd"
    - "*.qmd"
    - "!semana*/"

website:
  title: "CCO221 - Métodos y técnicas de investigación 1"
  navbar:
    left:
      - href: index.qmd
        text: Acerca de
      - text: Clases prácticas
        menu: 
          - href: semana10.qmd
            text: Semana 10

format:
  html:
    lang: es
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute: 
  freeze: auto # re-render only when source changes

