project:
  type: website
  render: 
    - "*.Rmd"
    - "*.rmd"
    - "*.qmd"
    - "!semana*/"

website:
  title: "CCO221 - Métodos y técnicas de investigación 1"
  navbar:
    left:
      - href: index.qmd
        text: Acerca de
      - text: Clases teóricas
        menu: 
          - href: semana10_teoria.qmd
            text: Semana 10
          - href: semana11_teoria.qmd
            text: Semana 11
          - href: semana12_teoria.qmd
            text: Semana 12
      - text: Clases prácticas
        menu: 
          - href: semana10.qmd
            text: Semana 10
          - href: semana11.qmd
            text: Semana 11
          - href: semana12.qmd
            text: Semana 12
      - text: Ejercicios
        menu: 
          - href: semana13_ejercicios.qmd
            text: Semana 13


format:
  html:
    lang: es
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute: 
  freeze: auto # re-render only when source changes

