---
title: "Clase teórica Semana 13"
subtitle: "pruebas bivariadas"
author: "Marylia Cruz"
date: "2025-06-09"
format: html
execute: 
  echo: true
  message: false
df-print: paged
code-annotations: hover
---

# Abrir la base de datos

```{r}
library(rio)
data=import("data/Data_ejemplo_comunica.xlsx")
```

```{r}
names(data)
```

# Prueba T de student

```{r}
t.test(`Tiempo en redes sociales` ~ `Le gusta Leer`, data = data)
```


```{r}
library(dplyr)
library(lsr)
tabla=data%>%
  group_by(`Le gusta Leer`)%>%
  summarise(
  promedio=mean(`Tiempo en redes sociales`),
  linferior=ciMean(`Tiempo en redes sociales`)[1],
    lsuperior=ciMean(`Tiempo en redes sociales`)[2]
)

tabla
```
# Gráfico de prueba T

```{r}
library(ggplot2)
ggplot(tabla, aes(x = `Le gusta Leer`, y = promedio)) +
  geom_errorbar(aes(ymin = linferior, ymax = lsuperior), width = 0.2) +
  labs(x = "Le gusta leer o no", y = "Media ± IC 95%") +
  theme_minimal()
```

# Prueba Anova 

```{r}
anova=aov(`Numero de Seguidores` ~`RedSocial`,data=data)

summary(anova)
```


# Gráfico de prueba Anova

```{r}
library(dplyr)
library(lsr)
tabla=data%>%
  group_by(`RedSocial`)%>%
  summarise(
  promedio=mean(`Numero de Seguidores`),
  linferior=ciMean(`Numero de Seguidores`)[1],
    lsuperior=ciMean(`Numero de Seguidores`)[2]
  
)

tabla
```

```{r}
library(ggplot2)
ggplot(tabla, aes(x = RedSocial, y = promedio)) +
  geom_errorbar(aes(ymin = linferior, ymax = lsuperior), width = 0.2) +
  labs(x = "Grupo", y = "Media ± IC 95%") +
  theme_minimal()
```


# Prueba de Correlación

```{r}
cor.test(data$`Numero de Seguidores`,data$`Numero de interacciones diarias`)
```

# Gráfico de dispersión

```{r}
library(ggplot2)

ggplot(data, aes(x = `Numero de Seguidores`, y = `Numero de interacciones diarias`)) +
  geom_point() +
  labs(title = "Diagrama de dispersión", x = "Eje X", y = "Eje Y") +
  theme_minimal()
```



